# -*- mode: python ; coding: utf-8 -*-
# PyInstaller spec file for MA Grader Backend

import os
import sys

block_cipher = None

# Get the directory containing this spec file
spec_dir = os.path.dirname(os.path.abspath(SPEC))

a = Analysis(
    ['server.py'],
    pathex=[spec_dir],
    binaries=[],
    datas=[
        ('graders', 'graders'),
        ('orchestrator', 'orchestrator'),
        ('utilities', 'utilities'),
        ('writers', 'writers'),
        ('templates', 'templates'),
        ('feedback', 'feedback'),
    ],
    hiddenimports=[
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'fastapi',
        'pydantic',
        'starlette',
        'openpyxl',
        'openpyxl.chart',
        'openpyxl.chart.scatter_chart',
        'openpyxl.chart.series',
        'openpyxl.chart.trendline',
        'requests',
        # Local modules - ensure they're bundled as importable
        'graders',
        'graders.income_analysis',
        'graders.income_analysis.grade_income_analysis',
        'graders.income_analysis.check_scatterplot',
        'graders.income_analysis.check_name_present',
        'graders.income_analysis.check_slope_intercept',
        'graders.income_analysis.check_slope_intercept_formatting',
        'graders.income_analysis.check_predictions',
        'graders.income_analysis.check_predictions_formatting',
        'graders.currency_conversion',
        'graders.currency_conversion.grade_currency_conversion_tab_v2',
        'graders.currency_conversion.row15_name_letters_v2',
        'graders.currency_conversion.row16_country_selection_v2',
        'graders.currency_conversion.row17_date_entries_v2',
        'graders.currency_conversion.row18_currency_codes_v2',
        'graders.currency_conversion.row19_exchange_rates_v2',
        'graders.currency_conversion.row20_budget_conversion_v2',
        'graders.currency_conversion.row21_usd_conversion_back_v2',
        'graders.currency_conversion.currency_lookup',
        'graders.unit_conversions',
        'orchestrator',
        'orchestrator.grade_single',
        'orchestrator.phase1_grade_all',
        'orchestrator.phase2_export_charts',
        'orchestrator.phase3_insert_charts',
        'orchestrator.phase4_cleanup',
        'writers',
        'writers.write_income_analysis_scores',
        'writers.write_currency_conversion_results_v2',
        'writers.write_unit_conversions_scores_v2',
        'writers.create_grading_sheet',
        'writers.export_chart_to_image',
        'utilities',
        'utilities.feedback_renderer',
        'utilities.json_loader',
        'utilities.paths',
        'utilities.validate_submission',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='ma-grader-server',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,  # Set to False for production
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
